version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin.123
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"